name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
